### ISSUE TITLE
click navigation is off by 4/5 pixels

### ISSUE THREAD

**Issue by daleharvey** [whiskyweb/whiskyweb-website#14]
obvious when you click speakers

**Comment by juokaz** [comment]
I think it might have something to do with this:

```
var sections = ['#home', '#information', '#speakers', '#sponsors', '#tickets'];
var positions = $.map(sections, function(id) {
  return $(id).position().top;
});
```

maybe not all images are loaded once that's called. If I reinitialize the WhiskyWeb object it works fine (as it recalculates those)

**Comment by juokaz** [comment]
Wrong button

**Comment by daleharvey** [comment]
This is fixed, likely something that didnt have an explicit height set
