### ISSUE TITLE
Early Tickets text

### ISSUE THREAD

**Issue by mgdm** [whiskyweb/whiskyweb-website#28]
Are only Early Tickets £75 as in the device at the top right? Should that just read 'tickets'?

**Comment by juokaz** [comment]
I'm thinking "One Price" or "The Price"?..

**Comment by mgdm** [comment]
Well, if we're doing student tickets, we might need to mention that too.

**Comment by juokaz** [comment]
We are doing student tickets, but it makes sense to promote the normal price on the homepage (that seems to be done by others too, student ticket is kind of a discount).

**Comment by juokaz** [comment]
Fixed by making it "Tickets only"
