### ISSUE TITLE
Navigation breaks on iPad 2

### ISSUE THREAD

**Issue by d0ugal** [whiskyweb/whiskyweb-website#8]
I've spent a bit of time trying to figure out why, but I can tell. When viewing the website on an iPad the first navigation tap works, after that the navigation becomes unresponsive and doesn't work.

Fairly low priority I'm sure as you can still scroll but I thought I'd let you know.

**Comment by jaytaph** [comment]
Took a look at it but I'm really not into javascript. All I can see is that as soon as you move the content a bit, the navigation starts working again. The unresponsiveness starts as soon as you do the jquery animation.

**Comment by jaytaph** [comment]
And in all fairness: http://events.jquery.org/2012/uk/  has the same problems :-)

**Comment by d0ugal** [comment]
Ha, well spotted. Maybe we can just leave it then. I might have a look tonight - didn't spot that it started working again in you moved the content a little.

**Comment by d0ugal** [comment]
This issue seems to have changed slightly. The navigation bar no longer moves down the page when clicking a link. It only moves when scrolling.
